version: "3.5"

services:

  nginx:
    build: ./docker/nginx
    container_name: memman_nginx
    ports:
      - "80:80"
    volumes:
      - src:/var/www/html
    depends_on: 
      - php
      - postgresql
    networks:
      - memman

  php:
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: prod
    container_name: memman_php
    ports:
      - "9000:9000"
    volumes: 
      - src:/var/www/html
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - memman

  postgresql:
    build: 
      context: ./docker/postgres
      target: prod
    container_name: memman_postgresql
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: memman
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - memman

  npm:
    image: node:14.15-alpine
    container_name: memman_node
    volumes: 
      - src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]

networks:
  memman:
    name: memman

volumes:
  src:
  db:
