version: "3.5"

services:

  nginx:
    build: ./docker/nginx
    container_name: memman_nginx
    ports:
      - "80:80"
    volumes:
      - src:/var/www/html
    depends_on: 
      - php
      - postgresql
    networks:
      - memman

  php:
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: prod
    container_name: memman_php
    ports:
      - "9000:9000"
    volumes: 
      - src:/var/www/html
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      DB_PASSWORD: ${DB_PASSWORD}
      NODE_ENV: ${APP_ENV}
    depends_on: 
      - postgresql
    entrypoint: ./init.sh
    networks:
      - memman

  postgresql:
    build: 
      context: ./docker/postgresql
      target: prod
    container_name: memman_postgresql
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: memman
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - memman

networks:
  memman:
    name: memman

volumes:
  src:
  db:
