version: "3.5"

networks:
  memman:
    name: memman

services:

  nginx:
    image: nginx:stable-alpine
    container_name: memman_nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - postgresql
    networks:
      - memman

  php:
    build: ./docker/php
    container_name: memman_php
    ports:
      - "9000:9000"
    volumes: 
      - ./src:/var/www/html
    networks:
      - memman

  postgresql:
    image: postgres:13.1-alpine
    container_name: memman_postgresql
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: memman
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - memman

  composer:
    image: composer:2
    container_name: memman_composer
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["composer"]
    networks:
      - memman

  npm:
    image: node:14.15-alpine
    container_name: memman_node
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - memman